SUBROUTINE TRIANGLE_GRID_EDGE

    !  This program is used to define the non-overlapped, unstructured             !
    !  triangular meshes used for flux computations. The mesh could be             !
    !  created using the commerical software called "sms8.0" or other              !
    !  mesh generation programs. The mesh file generated by sms8.0 can             !
    !  be directly used for this subroutine, while the mesh file                   !
    !  generated using other programs must be coverted the data format             !
    !  to meet the required format used here.                                      !

    !     variable list:
    !  vx(m)    :: vx(i) = x-coordinate of node i (input from mesh)
    !  vy(m)    :: vy(i) = y-coordinate of node i (input from mesh)
    !  nv(n,3)  :: nv(i:1-3) = 3 node numbers of element i
    !  xc(n)    :: xc(i) = x-coordinate of element i (calculated from vx)          !
    !  yc(n)    :: yc(i) = y-coordinate of element i (calculated from vy)          !
    !                                                                              !
    !  nbe(n,3) :: nbe(i,1->3) = element index of 1->3 neighbors of element i      !
    !  isbce(n) :: flag if element is on the boundary, see below for values        !
    !  isonb(m) :: flag is node is on the boundary, see below for values           !
    !                                                                              !
    !  ntve(m)  :: the number of neighboring elements of node m                    !
    !  nbve(m,ntve(m)) :: nbve(i,1->ntve(i)) = ntve elements containing node i     !
    !  nbvt(m,ntve(m)) :: nbvt(i,j) = the node number of node i in element         !
    !                     nbve(i,j) (has a value of 1,2,or 3)                      !
    !                                                                              !
    !classification of the triangles nodes, and edges                         !
    !                                                                              !
    !     isonb(i)=0:  node in the interior computational domain                   !
    !     isonb(i)=1:  node on the solid boundary                                  !
    !     isonb(i)=2:  node on the open boundary                                   !
    !                                                                              !
    !     isbce(i)=0:  element in the interior computational domain                !
    !     isbce(i)=1:  element on the solid boundary                               !
    !     isbce(i)=2:  element on the open boundary                                !
    !     isbce(i)=3:  element with 2 solid boundary edges                         !

    use ALL_VARS
    implicit none

    integer, allocatable, dimension(:, :) :: NB_TMP, CELLS, NBET
    integer, allocatable, dimension(:)   :: CELLCNT
    integer :: ii, jj, kk, ll, NTMP, NCNT, NFLAG, JJB, N1, N2, N3, J1, J2, J3
    real(sp) :: X1, X2, X3, Y1, Y2, Y3, DELT, AI1, AI2, AI3, BI1, BI2, BI3, CI1, CI2, CI3, DELTX, DELTY, B1, B2, ART(N)


    ! SET UP MESH (HORIZONTAL COORDINATES)
    ! CALCULATE GLOBAL MINIMUMS AND MAXIMUMS
    VXMIN = MINVAL(VX(1:M)) ; VXMAX = MAXVAL(VX(1:M))
    VYMIN = MINVAL(VY(1:M)) ; VYMAX = MAXVAL(VY(1:M))

    ! SHIFT GRID TO UPPER RIGHT CARTESIAN
    VX = VX - VXMIN
    VY = VY - VYMIN

    ! CALCULATE GLOBAL ELEMENT CENTER GRID COORDINATES
    do ii = 1, N
        XC(ii) = (VX(NV(ii, 1)) + VX(NV(ii, 2)) + VX(NV(ii, 3)))/3.0_SP
        YC(ii) = (VY(NV(ii, 1)) + VY(NV(ii, 2)) + VY(NV(ii, 3)))/3.0_SP
    end do

    XC(0) = 0.0_SP ; YC(0) = 0.0_SP

    ART  = 0.0_SP
    do ii = 1, N
        ART(ii) = (VX(NV(ii, 2)) - VX(NV(ii, 1))) * (VY(NV(ii, 3)) - VY(NV(ii, 1))) - (VX(NV(ii, 3)) - VX(NV(ii, 1))) * (VY(NV(ii, 2)) - VY(NV(ii, 1)))
    end do
    ART = ABS(0.5_SP*ART)

    ! INITIALIZE
    ISBCE = 0
    ISONB = 0
    NBE   = 0

    ! DETERMINE NBE(i=1:n,j=1:3): INDEX OF 1 to 3 NEIGHBORING ELEMENTS
    allocate(NBET(N, 3)) ; NBET = 0
    allocate(CELLS(M, 50)) ; CELLS = 0
    allocate(CELLCNT(M))  ; CELLCNT = 0

    do ii = 1, N
        N1 = NV(ii, 1) ; CELLCNT(N1) = CELLCNT(N1)+1
        N2 = NV(ii, 2) ; CELLCNT(N2) = CELLCNT(N2)+1
        N3 = NV(ii, 3) ; CELLCNT(N3) = CELLCNT(N3)+1
        CELLS(NV(ii, 1), CELLCNT(N1)) = ii
        CELLS(NV(ii, 2), CELLCNT(N2)) = ii
        CELLS(NV(ii, 3), CELLCNT(N3)) = ii
    end do

    if (maxval(cellcnt) > 50) write(*, *) 'bad', maxval(cellcnt)

    DO ii = 1, N
        N1 = NV(ii,1)
        N2 = NV(ii,2)
        N3 = NV(ii,3)
        DO J1 = 1, CELLCNT(N1)
            DO J2 = 1, CELLCNT(N2)
                IF ((CELLS(N1, J1) == CELLS(N2, J2)) .AND. CELLS(N1,J1) /= ii) NBE(ii, 3) = CELLS(N1, J1)
            END DO
        END DO
        DO J2 = 1, CELLCNT(N2)
            DO J3 = 1, CELLCNT(N3)
                IF ((CELLS(N2, J2) == CELLS(N3, J3)) .AND. CELLS(N2, J2) /= ii) NBE(ii,1) = CELLS(N2, J2)
            END DO
        END DO
        DO J1 = 1, CELLCNT(N1)
            DO J3 = 1, CELLCNT(N3)
                IF((CELLS(N1, J1) == CELLS(N3,J3)) .AND. CELLS(N1,J1) /= ii) NBE(ii, 2) = CELLS(N3, J3)
            END DO
        END DO
    END DO
    DEALLOCATE(CELLS,CELLCNT)

    !   IF(MSR)WRITE(IPT,*)  '!  NEIGHBOR FINDING      :    COMPLETE'
    !
    ! Ensure all elements have at least one neighbor
    NFLAG = 0
    do ii = 1, N
        if (sum(NBE(ii, 1:3)) == 0) then
            NFLAG = 1
            write(*, *) 'ELEMENT ', ii, ' AT ', XC(ii), YC(ii), ' HAS NO NEIGHBORS'
            stop
        end if
    end do
    if (NFLAG == 1) stop


    ! if element on boundary set isbce(i)=1 and isonb(j)=1 for boundary nodes j
    do ii = 1, N
        if ( MIN(NBE(ii, 1), NBE(ii, 2), NBE(ii, 3)) == 0 ) then
            ISBCE(ii) = 1  ! element on boundary
            if (NBE(ii, 1) == 0) then
                ISONB(NV(ii, 2)) = 1 ; ISONB(NV(ii, 3)) = 1
            end if
            if (NBE(ii,2) == 0) then
                ISONB(NV(ii, 1)) = 1 ; ISONB(NV(ii, 3)) = 1
            end if
            if (NBE(ii,3) == 0) then
                ISONB(NV(ii, 1)) = 1 ; ISONB(NV(ii, 2)) = 1
            end if
        end if
    end do

    ! DEFINE NTVE, NBVE, NBVT
    ! ntve(1:m): total number of the surrounding triangles connected to the given node
    ! nbve(1:m, 1:ntve+1): the identification number of surrounding triangles with a common node (counted clockwise)
    ! nbvt(1:m,ntve(1:m)): the idenfication number of a given node over each individual surrounding triangle(counted clockwise)                                              !

    ! Determine max number of surrounding elements
    MX_NBR_ELEM = 0
    element_loop: do ii = 1, M
        NCNT = 0
        node_loop: do jj = 1, N
            if ( float(NV(jj, 1) - ii) * float(NV(jj, 2) - ii) * float(NV(jj, 3) - ii) == 0.0_SP ) NCNT = NCNT + 1
        end do node_loop
        MX_NBR_ELEM = MAX(MX_NBR_ELEM, NCNT)
    end do element_loop


    ! allocate arrays based on mx_nbr_elem
    ALLOCATE( NBVE(M, MX_NBR_ELEM + 1))
    ALLOCATE( NBVT(M, MX_NBR_ELEM + 1))


    ! Determine number of surrounding elements for node i = ntve(i)
    ! determine nbve - indices of neighboring elements of node i
    ! determine nbvt - index (1,2, or 3) of node i in neighboring element

    do ii = 1, M
        NCNT = 0
        do jj = 1, N
            if ( float(NV(jj, 1) - ii) * float(NV(jj, 2) - ii) * float(NV(jj, 3) - ii) == 0.0_SP) then
                NCNT = NCNT+1
                NBVE(ii, NCNT) = jj
                if ((NV(jj, 1) - ii) == 0) NBVT(ii, NCNT) = 1
                if ((NV(jj, 2) - ii) == 0) NBVT(ii, NCNT) = 2
                if ((NV(jj, 3) - ii) == 0) NBVT(ii, NCNT) = 3
            end if
        end do
        NTVE(ii) = NCNT
    end do

    !
    !--Reorder Order Elements Surrounding a Node to Go in a Cyclical Procession----!
    !--Determine NTSN  = Number of Nodes Surrounding a Node (+1)-------------------!
    !--Determine NBSN  = Node Numbers of Nodes Surrounding a Node------------------!

    allocate(NB_TMP(M,MX_NBR_ELEM+1))
    do ii = 1, M
        if (ISONB(ii) == 0) then
            NB_TMP(1, 1) = NBVE(ii, 1)
            NB_TMP(1, 2) = NBVT(ii, 1)
            do jj = 2, NTVE(ii) + 1
                kk = NB_TMP(jj - 1, 1)
                ll = NB_TMP(jj - 1, 2)
                NB_TMP(jj, 1) = NBE(kk, ll + 1 - INT((ll + 1)/4)*3)
                ll=NB_TMP(jj, 1)
                IF ((NV(ll, 1) - ii) == 0) NB_TMP(jj, 2) = 1
                IF ((NV(ll, 2) - ii) == 0) NB_TMP(jj, 2) = 2
                IF ((NV(ll, 3) - ii) == 0) NB_TMP(jj, 2) = 3
            end do

            do jj = 2, NTVE(ii) + 1
                NBVE(ii, jj) = NB_TMP(jj, 1)
            end do

            do jj = 2, NTVE(ii) + 1
                NBVT(ii, jj) = NB_TMP(jj, 2)
            end do

            NTMP = NTVE(ii) + 1
            if (NBVE(ii, 1) /= NBVE(ii, NTMP)) then
                print*, ii,'nbve(ii) not correct!!'
                stop
            end if
            if (NBVT(ii,1) /= NBVT(ii, NTMP)) then
                print*, ii,'NBVT(ii) NOT CORRECT!!'
                stop
            end if

        else
            JJB = 0

            do jj = 1, NTVE(ii)
                ll = NBVT(ii, jj)
                if (NBE(NBVE(ii, jj), ll + 2 - int((ll + 2)/4)*3) == 0) then
                    JJB = JJB + 1
                    NB_TMP(JJB, 1) = NBVE(ii, jj)
                    NB_TMP(JJB, 2) = NBVT(ii, jj)
                end if
            end do

            if (JJB /= 1) then
                print*, 'ERROR IN ISONB !, I, J', ii, jj
                stop
            end if

            do jj = 2, NTVE(ii)
                kk = NB_TMP(jj - 1, 1)
                ll = NB_TMP(jj - 1, 2)
                NB_TMP(jj, 1) = NBE(kk, ll + 1 - int((ll + 1)/4)*3)
                ll = NB_TMP(jj, 1)
                if ((NV(ll, 1) - ii) == 0) NB_TMP(jj, 2) = 1
                if ((NV(ll, 2) - ii) == 0) NB_TMP(jj, 2) = 2
                if ((NV(ll, 3) - ii) == 0) NB_TMP(jj, 2) = 3
            end do

            do jj = 1, NTVE(ii)
                NBVE(ii, jj) = NB_TMP(jj, 1)
                NBVT(ii, jj) = NB_TMP(jj, 2)
            enddo

            NBVE(ii, NTVE(ii) + 1) = 0
        end if
    end do
    deallocate(NB_TMP)

    !--Huang change 911
    ! This is a special part. Since in original FVCOM subroutine tge.F
    !       ISONB(I_OBC_N(I)) = 2
    ! I_OBC_N is read from input file xxx_obc.dat
    ! here Martin deleted that part
    ! This line of code needs to be changed for each new case
    !   do i=1,135
    !      ISONB(i) = 2
    !   enddo


    do ii = 1, N
        if (ISBCE(ii) == 0) then
            Y1 = YC(NBE(ii, 1)) - YC(ii)
            Y2 = YC(NBE(ii, 2)) - YC(ii)
            Y3 = YC(NBE(ii, 3)) - YC(ii)
            X1 = XC(NBE(ii, 1)) - XC(ii)
            X2 = XC(NBE(ii, 2)) - XC(ii)
            X3 = XC(NBE(ii, 3)) - XC(ii)
            X1 = X1/1000.0_SP
            X2 = X2/1000.0_SP
            X3 = X3/1000.0_SP
            Y1 = Y1/1000.0_SP
            Y2 = Y2/1000.0_SP
            Y3 = Y3/1000.0_SP

            delt=(x1*y2-x2*y1)**2+(x1*y3-x3*y1)**2+(x2*y3-x3*y2)**2
            delt=delt*1000.0

            a1u(ii, 1) = (y1+y2+y3)*(x1*y1+x2*y2+x3*y3)- (x1+x2+x3)*(y1**2+y2**2+y3**2)
            a1u(ii, 1) = a1u(ii, 1)/delt
            a1u(ii, 2) = (y1**2+y2**2+y3**2)*x1 - (x1*y1+x2*y2+x3*y3)*y1
            a1u(ii, 2) = a1u(ii, 2)/delt
            a1u(ii, 3) = (y1**2+y2**2+y3**2)*x2 - (x1*y1+x2*y2+x3*y3)*y2
            a1u(ii, 3) = a1u(ii, 3)/delt
            a1u(ii, 4) = (y1**2+y2**2+y3**2)*x3 - (x1*y1+x2*y2+x3*y3)*y3
            a1u(ii, 4) = a1u(ii, 4)/delt

            a2u(ii, 1) = (x1+x2+x3)*(x1*y1+x2*y2+x3*y3) - (y1+y2+y3)*(x1**2+x2**2+x3**2)
            a2u(ii, 1) = a2u(ii, 1)/delt
            a2u(ii, 2) = (x1**2+x2**2+x3**2)*y1-(x1*y1+x2*y2+x3*y3)*x1
            a2u(ii, 2) = a2u(ii, 2)/delt
            a2u(ii, 3) = (x1**2+x2**2+x3**2)*y2-(x1*y1+x2*y2+x3*y3)*x2
            a2u(ii, 3) = a2u(ii, 3)/delt
            a2u(ii, 4) = (x1**2+x2**2+x3**2)*y3-(x1*y1+x2*y2+x3*y3)*x3
            a2u(ii, 4) = a2u(ii, 4)/delt
        end if

        x1 = vx(nv(ii, 1)) - xc(ii)
        x2 = vx(nv(ii, 2)) - xc(ii)
        x3 = vx(nv(ii, 3)) - xc(ii)
        y1 = vy(nv(ii, 1)) - yc(ii)
        y2 = vy(nv(ii, 2)) - yc(ii)
        y3 = vy(nv(ii, 3)) - yc(ii)


        ai1 = y2 - y3
        ai2 = y3 - y1
        ai3 = y1 - y2
        bi1 = x3 - x2
        bi2 = x1 - x3
        bi3 = x2 - x1
        ci1 = x2*y3 - x3*y2
        ci2 = x3*y1 - x1*y3
        ci3 = x1*y2 - x2*y1

        aw0(ii, 1) = -ci1 / 2.0 / art(ii)
        aw0(ii, 2) = -ci2 / 2.0 / art(ii)
        aw0(ii, 3) = -ci3 / 2.0 / art(ii)
        awx(ii, 1) = -ai1 /2.0 / art(ii)
        awx(ii, 2) = -ai2 / 2.0 / art(ii)
        awx(ii, 3) = -ai3 / 2.0 / art(ii)
        awy(ii, 1) = -bi1 / 2.0 / art(ii)
        awy(ii, 2) = -bi2 / 2.0 / art(ii)
        awy(ii, 3) = -bi3 / 2.0 / art(ii)

    end do

    do ii = 1, n
        if (isbce(ii) > 1) then
            do jj = 1, 4
                a1u(ii, jj) = 0.0_SP
                a2u(ii, jj) = 0.0_SP
            end do
        else if (isbce(ii) == 1) then
            do jj = 1, 3
                if (nbe(ii, jj) == 0) ll = jj
            end do
            j1 = ll + 1 - int((ll + 1)/4)*3
            j2 = ll + 2 - int((ll + 2)/4)*3
            x1 = vx(nv(ii, j1)) - xc(ii)
            x2 = vx(nv(ii, j2)) - xc(ii)
            y1 = vy(nv(ii, j1)) - yc(ii)
            y2 = vy(nv(ii, j2)) - yc(ii)

            delt = x1*y2 - x2*y1
            b1 = (y2 - y1)/delt
            b2 = (x1 - x2)/delt
            deltx = vx(nv(ii, j1)) - vx(nv(ii, j2))
            delty = vy(nv(ii, j1)) - vy(nv(ii, j2))


            a1u(ii, 1) = 0.0_SP
            a1u(ii, ll + 1) = 0.0_SP
            a1u(ii, j1 + 1) = 0.0_SP
            a1u(ii, j2 + 1) = 0.0_SP

            a2u(ii, 1) = 0.0_SP
            a2u(ii, ll + 1) = 0.0_SP
            a2u(ii, j1 + 1) = 0.0_SP
            a2u(ii, j2 + 1) = 0.0_SP
        end if
    end do

end subroutine TRIANGLE_GRID_EDGE
